---@meta
---@diagnostic disable

---For LuaRules/Gaia (synced) only
---
---[View documents](https://springrts.com/wiki/Lua_ConstCOB)
---@class ConstCOBexplode
---@field SHATTER        COBexplode
---@field EXPLODE        COBexplode
---@field EXPLODE_ON_HIT COBexplode
---@field FALL           COBexplode
---@field SMOKE          COBexplode
---@field FIRE           COBexplode
---@field NONE           COBexplode
---@field NO_CEG_TRAIL   COBexplode
---@field NO_HEATCLOUD   COBexplode
---@field RECURSIVE      COBexplode # New in version 99.0


---For LuaRules/Gaia (synced) only
---
---[View documents](https://springrts.com/wiki/Lua_ConstCOB)
---@class ConstCOBemitSfx
---@field VTOL            COBemitSfx
---@field WAKE            COBemitSfx
---@field REVERSE_WAKE    COBemitSfx
---@field WHITE_SMOKE     COBemitSfx
---@field BLACK_SMOKE     COBemitSfx
---@field BUBBLE          COBemitSfx
---@field CEG             COBemitSfx
---@field FIRE_WEAPON     COBemitSfx
---@field DETONATE_WEAPON COBemitSfx
---@field GLOBAL          COBemitSfx


---For LuaRules/Gaia (synced) only
---
---[View documents](https://springrts.com/wiki/Lua_ConstCOB)
---@class ConstCOBgetSet
---@field ACTIVATION         COBgetSet
---@field STANDINGMOVEORDERS COBgetSet
---@field STANDINGFIREORDERS COBgetSet
---@field HEALTH             COBgetSet
---@field INBUILDSTANCE      COBgetSet
---@field BUSY               COBgetSet
---@field PIECE_XZ           COBgetSet
---@field PIECE_Y            COBgetSet
---@field UNIT_XZ            COBgetSet
---@field UNIT_Y             COBgetSet
---@field UNIT_HEIGHT        COBgetSet
---@field XZ_ATAN            COBgetSet
---@field XZ_HYPOT           COBgetSet
---@field ATAN               COBgetSet
---@field HYPOT              COBgetSet
---@field GROUND_HEIGHT      COBgetSet
---@field BUILD_PERCENT_LEFT COBgetSet
---@field YARD_OPEN          COBgetSet
---@field BUGGER_OFF         COBgetSet
---@field ARMORED            COBgetSet
---@field IN_WATER           COBgetSet
---@field CURRENT_SPEED      COBgetSet
---@field VETERAN_LEVEL      COBgetSet
---@field ON_ROAD            COBgetSet
---@field MAX_ID             COBgetSet
---@field MY_ID              COBgetSet
---@field UNIT_TEAM          COBgetSet
---@field UNIT_BUILD_PERCENT_LEFT COBgetSet
---@field UNIT_ALLIED         COBgetSet
---@field MAX_SPEED           COBgetSet
---@field CLOAKED             COBgetSet
---@field WANT_CLOAK          COBgetSet
---@field GROUND_WATER_HEIGHT COBgetSet
---@field UPRIGHT          COBgetSet
---@field POW              COBgetSet
---@field PRINT            COBgetSet
---@field HEADING          COBgetSet
---@field TARGET_ID        COBgetSet
---@field LAST_ATTACKER_ID COBgetSet
---@field LOS_RADIUS       COBgetSet
---@field AIR_LOS_RADIUS   COBgetSet
---@field RADAR_RADIUS     COBgetSet
---@field JAMMER_RADIUS    COBgetSet
---@field SONAR_RADIUS     COBgetSet
---@field SONAR_JAM_RADIUS COBgetSet
---@field SEISMIC_RADIUS   COBgetSet
---@field DO_SEISMIC_PING  COBgetSet
---@field CURRENT_FUEL     COBgetSet
---@field TRANSPORT_ID     COBgetSet
---@field SHIELD_POWER     COBgetSet
---@field STEALTH          COBgetSet
---@field CRASHING         COBgetSet
---@field CHANGE_TARGET    COBgetSet
---@field CEG_DAMAGE       COBgetSet
---@field COB_ID           COBgetSet
---@field PLAY_SOUND       COBgetSet
---@field PLAY_SOUND       COBgetSet
---@field KILL_UNIT        COBgetSet
---@field ALPHA_THRESHOLD  COBgetSet
---@field SET_WEAPON_UNIT_TARGET COBgetSet
---@field SET_WEAPON_GROUND_TARGET COBgetSet
---@field SONAR_STEALTH COBgetSet
---@field REVERSING     COBgetSet
---@field FLANK_B_MODE  COBgetSet
---@field FLANK_B_DIR   COBgetSet
---@field FLANK_B_MOBILITY_ADD COBgetSet
---@field FLANK_B_MAX_DAMAGE   COBgetSet
---@field FLANK_B_MIN_DAMAGE   COBgetSet
---@field WEAPON_RELOADSTATE   COBgetSet
---@field WEAPON_RELOADTIME    COBgetSet
---@field WEAPON_ACCURACY      COBgetSet
---@field WEAPON_SPRAY         COBgetSet
---@field WEAPON_RANGE         COBgetSet
---@field WEAPON_PROJECTILE_SPEED COBgetSet
---@field MIN COBgetSet
---@field MAX COBgetSet
---@field ABS COBgetSet
---@field GAME_FRAME COBgetSet


---For LuaRules/Gaia (synced) only
---
---[View documents](https://springrts.com/wiki/Lua_ConstCOB)
---@class COBexplode: uint
---For LuaRules/Gaia (synced) only
---
---[View documents](https://springrts.com/wiki/Lua_ConstCOB)
---@class COBemitSfx: uint
---For LuaRules/Gaia (synced) only
---
---[View documents](https://springrts.com/wiki/Lua_ConstCOB)
---@class COBgetSet: uint
